<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>.NET Platform Architecture</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <link rel="stylesheet" href="../../../out/res/bootstrap.css">
    <style>
        body {
    padding: 60px 60px 60px 100px;
    font-family: PF Regal,Georgia,serif;
    font-size: 16pt;
    font-weight: 300;
}

strong {
    font-weight: 500;
}

p, li {
    margin: 0 0 20px;
    line-height: 32px;
    font-family: inherit;
}

ol, ul {
    padding-left: 35px;
    margin-top: 1.1rem;
    margin-bottom: 1.1rem;
}

ol li {
    padding-left: 10px;	
    font-family: inherit;
}

ul li {
    padding-left: 12px;	
    font-family: inherit;
}

table {
    margin: 30px 0;
    width: 100%;
}

thead {                         
    background-color: aliceblue;
}

table th {
    font-weight: 400;
}

table td, table th {
    padding: 7px;
    border-top: solid darkgrey 1px;
    border-bottom: solid darkgrey 1px;
    border-right: dotted darkgray 1px;
    border-left: dotted darkgray 1px;
    font-size: smaller;
}

code, *[class^='lang-'] span, *[class^='lang-'] pre {
    font-family: JB Mono, monospace !important;
}

*[class^='lang-'] {
    padding: 4px 0px 14px 0px;
}


*[class^='lang-'] > div, pre > code {
    border-left-color: #eee;
    border-left-style: dotted;
    border-left-width: 3px;
    padding-left: 25px;
    display: block;
    background-color: aliceblue !important;
    padding-top: 20px;
    padding-bottom: 20px;
}

*[class^='lang-'] > div pre, pre > code pre {
    margin-bottom: 0;
}

p code:not(.highlight), li code:not(.highlight) {
    font-size: 16px;
    border: gainsboro;
    border-width: 1px;
    border-style: solid;
    padding: 4px;
    color: darkslateblue;
}

code.highlight {
    font-family: inherit !important;
    font-size: inherit;
    font-weight: inherit;
    color: inherit;
}

p code.highlight, li code.highlight {
    padding: 4px;
    background-color: #ffffa1;
}

*[class^='lang-'] span, *[class^='lang-'] pre, pre > code {
    font-size: 13px;
    line-height: 20px;
}

p a, li a {
    text-decoration: none;
    color: inherit;
    box-shadow: inset 0 -1px #b88b59;
}

blockquote h5 {
    background-color: aquamarine;
    margin: 16px 0 16px -20px;
    padding: 15px 30px 15px;
}

p img {
    width: 95%;
}

p:has( > img) {
    text-align: center;
}

blockquote > p.big-quote {
    margin: 40px 0 60px 0;
    font-family: Charter;
    font-size: 55px;
    line-height: 60px;
    width: 150%;
    padding: 0;
}

blockquote:not( p.big-quote) {
    background-color: lavenderblush;
    padding-left: 20px;
    border-left: 1px solid rgba(0,0,0,.08);
}

blockquote p {
    margin: 16px 0;
    padding: 12px 12px 13px;
    font-family: inherit;
}

blockquote p code {
    font-family: consolas, monospace;
    font-size: 17px;
    background-color: aliceblue;
    padding: 4px 6px;
}

h1, h2, h3, h4, h5, h6 {
    margin: 0;
    padding: 0;
    font-weight: 400;
    font-family: inherit;
}

h1 {
    font-size: 40px;
    font-family: PF Regal,Georgia,serif;
    font-weight: 300;
    margin: 40px 0 20px 0;
    border-bottom-style: ridge;
    padding-bottom: 10px;
}

h1 b {
    font-family: Proxima Nova,Arial,Helvetica Neue,sans-serif;
    font-weight: 700;
    font-size: 37px;
    line-height: 42px;
}

h2 {
    margin-top: 35px;
    margin-bottom: 10px;
    font-family: Proxima Nova,Arial,Helvetica Neue,sans-serif;
    font-size: 20px;
    font-weight: 700;
    line-height: 24px;
    border-bottom-color: grey;
    border-bottom-style: solid;
    padding-bottom: 5px;
}

h3 {
    margin: 30px 0 15px 0;
    font-size: 17pt;
    font-weight: 400;
}

h4 {
    margin: 20px 0 10px 0;
    font-size: 16pt;
    font-weight: 400;
}

/* Fonts */

/*@font-face {*/
/*    font-family: 'PF Regal';*/
/*    src: url('../../../out/res/fonts/PFRegalTextPro-RegularA.eot');*/
/*    src: local('../../../out/res/fonts/PFRegalTextPro-RegularA'),*/
/*        url('../../../out/res/fonts/PFRegalTextPro-RegularA.woff2') format('woff2'),*/
/*        url('../../../out/res/fonts/PFRegalTextPro-RegularA.woff') format('woff'),*/
/*        url('../../../out/res/fonts/PFRegalTextPro-RegularA.ttf') format('truetype');*/
/*    font-weight: 300;*/
/*    font-style: normal;*/
/*}*/

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-Bold.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-Bold'),
        url('../../../out/res/fonts/PFRegalTextPro-Bold.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-Bold.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-Medium.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-Medium'),
        url('../../../out/res/fonts/PFRegalTextPro-Medium.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-Medium.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-Medium.ttf') format('truetype');
    font-weight: 500;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-BlackItalic.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-BlackItalic'),
        url('../../../out/res/fonts/PFRegalTextPro-BlackItalic.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-BlackItalic.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-BlackItalic.ttf') format('truetype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-Black.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-Black'),
        url('../../../out/res/fonts/PFRegalTextPro-Black.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-Black.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-Black.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal UBlack';
    src: url('../../../out/res/fonts/PFRegalTextPro-UBlack.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-UBlack'),
        url('../../../out/res/fonts/PFRegalTextPro-UBlack.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-UBlack.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-UBlack.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-MediumItalic.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-MediumItalic'),
        url('../../../out/res/fonts/PFRegalTextPro-MediumItalic.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-MediumItalic.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-MediumItalic.ttf') format('truetype');
    font-weight: 500;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-UBlackItalic.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-UBlackItalic'),
        url('../../../out/res/fonts/PFRegalTextPro-UBlackItalic.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-UBlackItalic.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-UBlackItalic.ttf') format('truetype');
    font-weight: 900;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-RegularAItalic.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-RegularAItalic'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularAItalic.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularAItalic.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularAItalic.ttf') format('truetype');
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-BoldItalic.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-BoldItalic'),
        url('../../../out/res/fonts/PFRegalTextPro-BoldItalic.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-BoldItalic.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-BoldItalic.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
}

@font-face {
    font-family: 'Charter';
    src: url('../../../out/res/fonts/charter-regular.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}

/*  Regular B */
@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-RegularBItalic.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-RegularBItalic'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularBItalic.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularBItalic.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularBItalic.ttf') format('truetype');
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: 'PF Regal';
    src: url('../../../out/res/fonts/PFRegalTextPro-RegularB.eot');
    src: local('../../../out/res/fonts/PFRegalTextPro-RegularB'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularB.woff2') format('woff2'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularB.woff') format('woff'),
        url('../../../out/res/fonts/PFRegalTextPro-RegularB.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
}                
    </style>

<div class="row">
<div class="offset-1 col-6">
<p style="
    font-size: 70pt;
    margin: 85px 0 85px 0;
    text-align: center;
">a:
   </p>
    <h2 id="the-architecture-of-an-exceptional-situation">The architecture of an exceptional situation</h2>
<blockquote>
<p><a href="https://github.com/sidristij/dotnetbook/issues/51">A link to the discussion</a></p>
</blockquote>
<p>I guess one of the most important issues in this topic is building an exception handling architecture in your application. This is interesting for many reasons. And the main reason, I think, is an apparent simplicity, which you don’t always know what to do with. All the basic constructs such as <code>IEnumerable</code>, <code>IDisposable</code>, <code>IObservable</code>, etc. have this property and use it everywhere. On the one hand, their simplicity tempts to use these constructs in different situations. On the other hand, they are full of traps which you might not get out. It is possible that looking at the amount of information we will cover you’ve got a question: what is so special about exceptional situations?</p>
<p>However, to make conclusions about building the architecture of exception classes we should learn some details about their classification. Because before building a system of types that would be clear for the user of code, a programmer should determine when to choose the type of error and when to catch or skip exceptions. So, let’s classify the exceptional situations (not the types of exceptions) based on various features.</p>
<h3 id="based-on-a-theoretical-possibility-to-catch-a-future-exception">Based on a theoretical possibility to catch a future exception.</h3>
<p>Based on this feature we can divide exceptions into those that will be definitely caught and those that highly likely won’t be caught. Why do I say <em>highly likely</em>? Because there always be someone who will try to catch an exception while this is unnecessary.</p>
<p>First, let’s describe the first group of exceptions – those that should be caught.</p>
<p>In case of such exceptions we, on the one hand, say to our subsystem that we came to a state when there is no point in further actions with our data. On the other hand, we mean that nothing disastrous happened and we can find the way out of the situation by simply catching the exception. This property is very important as it defines the criticality of an error and gives confidence that if we catch an exception and clear resources, we can simply proceed with the code.</p>
<p>The second group deals with exceptions that, although it may sound strange, don’t have to be caught. They can be used only for error logging, but not for correcting a situation. The simplest example is <code>ArgumentException</code> and <code>NullReferenceException</code>. In fact, in an ordinary situation you don’t need to catch, for example, <code>ArgumentNullException</code> because in this case the source of an error is exactly you. If you catch such an exception, you admit that you made an error and passed something unacceptable to a method:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">void</span> SomeMethod(<span style="color:Blue;">object</span> argument)
{
    <span style="color:Blue;">try</span> {
        AnotherMethod(argument);
    } <span style="color:Blue;">catch</span> (ArgumentNullException exception)
    {
        <span style="color:Green;">// Log it</span>
    }
}
</pre></div>
</div>
<p>In this method we try to catch <code>ArgumentNullException</code>. But I think this is strange as passing right arguments to a method is entirely our concern. Reacting after the event would be incorrect: the best thing you can do in such a situation is to check the passed data in advance before calling a method or even to build such code where getting wrong parameters is impossible.</p>
<p>Another group of exceptional situations is fatal errors. If some cache is faulty and the work of a subsystem is anyway incorrect, then it is a fatal error and the nearest code on the stack will not catch it for sure:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
T GetFromCacheOrCalculate()
{
    <span style="color:Blue;">try</span> {
        <span style="color:Blue;">if</span>(_cache.TryGetValue(Key, <span style="color:Blue;">out</span> <span style="color:Blue;">var</span> result))
        {
            <span style="color:Blue;">return</span> result;
        } <span style="color:Blue;">else</span> {
            T res = Strategy(Key);
            _cache[Key] = res;
            <span style="color:Blue;">return</span> res;
        }
    } cache (CacheCorruptedException exception)
    {
        RecreateCache();
        <span style="color:Blue;">return</span> GetFromCacheOrCalculate();
    }
}
</pre></div>
</div>
<p><code>CacheCorruptedException</code> is an exception meaning that &laquo;hard drive cache is inconsistent&quot;. Then, if the cause of such an error is fatal for the cache subsystem (for example there are no cache file access rights), the following code can’t recreate cache using <code>RecreateCache</code> instruction and therefore catching this exception is an error itself.</p>
<h3 id="based-on-the-area-where-an-exceptional-situation-is-actually-catched">Based on the area where an exceptional situation is actually catched</h3>
<p>Another issue is whether we should catch some exceptions or pass them to somebody who understands the situation better. In other words, we should establish areas of responsibility. Let’s examine the following code:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>

<span style="color:Blue;">namespace</span> JetFinance.Strategies
{
    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> WildStrategy : StrategyBase
    {
        <span style="color:Blue;">private</span> Random random =  <span style="color:Blue;">new</span> Random();

        <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> PlayRussianRoulette()
        {
            <span style="color:Blue;">if</span>(DateTime.Now.Second == (random.Next() % 60))
            {
                <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> StrategyException();
            }
        }
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> StrategyException : Exception { <span style="color:Green;">/* .. */</span> }
}

<span style="color:Blue;">namespace</span> JetFinance.Investments
{
    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> WildInvestment
    {
        WildStrategy _strategy;

        <span style="color:Blue;">public</span> WildInvestment(WildStrategy strategy)
        {
            _strategy = strategy;
        }

        <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> DoSomethingWild()
        {
            ?<span style="color:Blue;">try</span>?
            {
                _strategy.PlayRussianRoulette();
            }
            <span style="color:Blue;">catch</span>(StrategyException exception)
            {
            }
        }
    }
}

<span style="color:Blue;">using</span> JetFinance.Strategies;
<span style="color:Blue;">using</span> JetFinance.Investments;

<span style="color:Blue;">void</span> Main()
{
    <span style="color:Blue;">var</span> foo = <span style="color:Blue;">new</span> WildStrategy();
    <span style="color:Blue;">var</span> boo = <span style="color:Blue;">new</span> WildInvestment(foo);

    ?<span style="color:Blue;">try</span>?
    {
        boo.DoSomethingWild();
    }
    <span style="color:Blue;">catch</span>(StrategyException exception)
    {
    }
}

</pre></div>
</div>
<p>Which of the two strategies is more appropriate? The area of responsibility is very important. Initially, it may seem that the work and consistency of <code>WildInvestment</code> fully depend on <code>WildStrategy</code>. Thus, if <code>WildInvestment</code> simply ignores this exception, it will go to the upper level and we shouldn’t do anything. However, note that in terms of architecture the <code>Main</code> method catches an exception from one level while calling the method from another. How does it look in terms of use? Well, that’s how it looks:</p>
<ul>
<li>the responsibility for this exception was handed over to us;</li>
<li>the user of this class is not sure that this exception was previously passed through a set of methods on purpose;</li>
<li>we start to create new dependencies which we got rid of by calling an intermediate layer.</li>
</ul>
<p>However, there is another conclusion resulting from this one: we should use <code>catch</code> in the <code>DoSomethingWild</code> method. And this is slightly strange for us: <code>WildInvestment</code> is sort of hardly dependent on something. I mean if <code>PlayRussianRoulette</code> didn’t work, the same will happen to <code>DoSomethingWild</code>: it doesn’t have return codes, but it has to play the roulette. So, what we can do in such a seemingly hopeless situation? The answer is actually simple: being on another level <code>DoSomethingWild</code> should throw its own exception that belongs to this level and wrap it in <code>InnerException</code> as the original source of a problem:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>

<span style="color:Blue;">namespace</span> JetFinance.Strategies
{
    pubilc <span style="color:Blue;">class</span> WildStrategy
    {
        <span style="color:Blue;">private</span> Random random =  <span style="color:Blue;">new</span> Random();

        <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> PlayRussianRoulette()
        {
            <span style="color:Blue;">if</span>(DateTime.Now.Second == (random.Next() % 60))
            {
                <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> StrategyException();
            }
        }
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> StrategyException : Exception { <span style="color:Green;">/* .. */</span> }
}

<span style="color:Blue;">namespace</span> JetFinance.Investments
{
    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> WildInvestment
    {
        WildStrategy _strategy;

        <span style="color:Blue;">public</span> WildInvestment(WildStrategy strategy)
        {
            _strategy = strategy;
        }

        <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> DoSomethingWild()
        {
            <span style="color:Blue;">try</span>
            {
                _strategy.PlayRussianRoulette();
            }
            <span style="color:Blue;">catch</span>(StrategyException exception)
            {
                <span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> FailedInvestmentException(<span style="color:#A31515;">&quot;Oops&quot;</span>, exception);
            }
        }
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> InvestmentException : Exception { <span style="color:Green;">/* .. */</span> }

    <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> FailedInvestmentException : Exception { <span style="color:Green;">/* .. */</span> }
}

<span style="color:Blue;">using</span> JetFinance.Investments;

<span style="color:Blue;">void</span> Main()
{
    <span style="color:Blue;">var</span> foo = <span style="color:Blue;">new</span> WildStrategy();
    <span style="color:Blue;">var</span> boo = <span style="color:Blue;">new</span> WildInvestment(foo);

    <span style="color:Blue;">try</span>
    {
        boo.DoSomethingWild();
    }
    <span style="color:Blue;">catch</span>(FailedInvestmentException exception)
    {
    }
}
</pre></div>
</div>
<p>By wrapping one exception in another we transfer the problem form one level of application to another and make its work more predictable in terms of a consumer of this class: the <code>Main</code> method.</p>
<h3 id="based-on-reuse-issues">Based on reuse issues</h3>
<p>Often we feel too lazy to create a new type of exception but when we decide to do it, it is not always clear which type to base on. But it is precisely these decisions that define the whole architecture of exceptional situations. Let’s have a look at some popular solutions and make some conclusions.</p>
<p>When choosing the type of exception we can use a previously made solution, i.e. to find an exception with the name that contains similar sense and use it. For example, if we got an entity via a parameter and we don’t like this entity, we can throw <code>InvalidArgumentException</code>, indicating the cause of an error in Message. This scenario looks good especially since <code>InvalidArgumentException</code> is in the group of exceptions that may not be caught. However, the choice of <code>InvalidDataException</code> will be wrong if you work with some data types. It is because this type is in <code>System.IO</code> area, which is probably isn’t what you deal with. Thus, it will almost always be wrong to search for an existing type instead of developing one by yourself. There are almost no exceptions for a general range of tasks. Virtually all of them are for specific situations and if you reuse them in other cases, it will gravely violate the architecture of exceptional situations. Moreover, an exception of a particular type (for example, <code>System.IO.InvalidDataException</code>) can confuse a user: on the one hand, he will see that exception belongs to the <code>System.IO</code> namespace, while on the other hand it is thrown from a completely different namespace. If this user starts thinking about the rules of throwing this exception, he may go to <a href="https://referencesource.microsoft.com/">referencesource.microsoft.com</a> and find <a href="https://referencesource.microsoft.com/#System/sys/System/IO/compression/InvalidDataException.cs,2b389f14fb01ad1b,references">all the places where it is thrown</a>:</p>
<ul>
<li><code>internal class System.IO.Compression.Inflater</code></li>
</ul>
<p>The user will understand that <del>somebody is all thumbs</del> this type of exception confused him as the method that threw this exception didn’t deal with compression.</p>
<p>Also, in terms of reuse, you can simply create one exception and declare the <code>ErrorCode</code> field in it. That seems like a good idea. You just throw the same exception, setting the code, and use just one <code>catch</code> to deal with exceptions, increasing the stability of an application, nothing more. However, I believe you should rethink this position. Of course, this approach makes life easier on the one hand. However, on the other hand, you dismiss the possibility to catch a subgroup of exceptions that have some common feature. For example, <code>ArgumentException</code> that unites a bunch of exceptions by inheritance. Another serious disadvantage is an excessively large and unreadable code that must arrange error code based filtering. However, introducing an encompassing type with an error code will be more appropriate when a user doesn’t have to care about specifying an error.</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> ParserException
{
    <span style="color:Blue;">public</span> ParserError ErrorCode { <span style="color:Blue;">get</span>; }

    <span style="color:Blue;">public</span> ParserException(ParserError errorCode)
    {
        ErrorCode = errorCode;
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">override</span> <span style="color:Blue;">string</span> Message
    {
        <span style="color:Blue;">get</span> {
            <span style="color:Blue;">return</span> Resources.GetResource($<span style="color:#A31515;">&quot;{nameof(ParserException)}{Enum.GetName(typeof(ParserError), ErrorCode)}&quot;</span>);
        }
    }
}

<span style="color:Blue;">public</span> <span style="color:Blue;">enum</span> ParserError
{
    MissingModifier,
    MissingBracket,
    <span style="color:Green;">// ...</span>
}

<span style="color:Green;">// Usage</span>
<span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> ParserException(ParserError.MissingModifier);
</pre></div>
</div>
<p>The code that protects the parser call doesn’t care why parsing failed: it is interested in the error as such. However, if the cause of fail becomes important after all, a user can always get the error code from the <code>ErrorCode</code> property. And you really don’t have to search for necessary words in a substring of <code>Message</code>.</p>
<p>If we don’t choose to reuse, we can create a type of exception for every situation. On the one hand, it sounds logical: one type of error – one type of exception. However, don’t overdo: having too many types of exceptions will cause the problem of catching them as the code of a calling method will be overloaded with <code>catch</code> blocks. Because it needs to process all types of exceptions that you want to pass to it. Another disadvantage is purely architectural. If you don’t use exceptions, you confuse those who will use these exceptions: they may have many things in common but will be caught separately.</p>
<p>However, there are great scenarios to introduce separate types for specific situations. For example, when the error affects not a whole entity, but a specific method. Then this error type should take such a place in the hierarchy of inheritance that no one would ever think to catch it together with something else: for example, through a separate branch of inheritance.</p>
<p>Also, if you combine both of these approaches, you can get a powerful set of instruments to work with a group of errors: you can introduce a common abstract type and inherit specific cases from it. The base class (our common type) must get an abstract property, designed to store an error code while inheritors will specify this code by overriding this property.</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">public</span> <span style="color:Blue;">abstract</span> <span style="color:Blue;">class</span> ParserException
{
    <span style="color:Blue;">public</span> <span style="color:Blue;">abstract</span> ParserError ErrorCode { <span style="color:Blue;">get</span>; }

    <span style="color:Blue;">public</span> <span style="color:Blue;">override</span> <span style="color:Blue;">string</span> Message
    {
        <span style="color:Blue;">get</span> {
            <span style="color:Blue;">return</span> Resources.GetResource($<span style="color:#A31515;">&quot;{nameof(ParserException)}{Enum.GetName(typeof(ParserError), ErrorCode)}&quot;</span>);
        }
    }
}

<span style="color:Blue;">public</span> <span style="color:Blue;">enum</span> ParserError
{
    MissingModifier,
    MissingBracket
}

<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> MissingModifierParserException : ParserException
{
    <span style="color:Blue;">public</span> <span style="color:Blue;">override</span> ParserError ErrorCode { <span style="color:Blue;">get</span>; } =&gt; ParserError.MissingModifier;
}

<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> MissingBracketParserException : ParserException
{
    <span style="color:Blue;">public</span> <span style="color:Blue;">override</span> ParserError ErrorCode { <span style="color:Blue;">get</span>; } =&gt; ParserError.MissingBracket;
}

<span style="color:Green;">// Usage</span>
<span style="color:Blue;">throw</span> <span style="color:Blue;">new</span> MissingModifierParserException(ParserError.MissingModifier);
</pre></div>
</div>
<p>Using this approach we get some wonderful properties:</p>
<ul>
<li>on the one hand, we keep catching exceptions using a base (common) type;</li>
<li>on the other hand, even catching exceptions with this base type we are still able to identify a specific situation;</li>
<li>plus, we can catch exceptions via a specific type instead of a base type without using the flat structure of classes.</li>
</ul>
<p>I think it is very convenient.</p>
<h3 id="based-on-belonging-to-a-specific-group-of-behavioral-situations">Based on belonging to a specific group of behavioral situations</h3>
<p>What conclusions can we make based on the previous reasoning? Let’s try to define them.</p>
<p>First of all, let’s decide what means a situation? Usually, we talk about classes and objects in terms of entities with some internal state and we can perform actions on these entities. Thus, the first type of behavioral situation includes actions on some entity. Next, if we look at an object graph from the outside we will see that it is logically represented as a combination of functional groups: the first group deals with caching, the second works with databases, the third performs mathematical calculations. Different layers can go through all these groups, e.g. layers of internal states logging, process logging, and method calls’ tracing. Layers can encompass several functional groups. For example, there can be a layer of a model, a layer of controllers and a presentation layer. These groups can be in one assembly or in different ones, but each group can create its own exceptional situations.</p>
<p>So, we can build a hierarchy for the types of exceptional situations based on the belonging of these types to one or another group or layer. Thus, we allow a catching code to easily navigate among these types in the hierarchy.</p>
<p>Let’s examine the following code:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>

<span style="color:Blue;">namespace</span> JetFinance
{
    <span style="color:Blue;">namespace</span> FinancialPipe
    {
        <span style="color:Blue;">namespace</span> Services
        {
            <span style="color:Blue;">namespace</span> XmlParserService
            {
            }

            <span style="color:Blue;">namespace</span> JsonCompilerService
            {
            }

            <span style="color:Blue;">namespace</span> TransactionalPostman
            {
            }
        }
    }

    <span style="color:Blue;">namespace</span> Accounting
    {
        <span style="color:Green;">/* ... */</span>
    }
}

</pre></div>
</div>
<p>What’s it like? I think the namespace is a perfect way to naturally group the types of exceptions based on the behavioral situations: everything that belongs to particular groups should stay there, including exceptions. Moreover, when you get a particular exception, you will see the name of its type and also its namespace that will specify a group it belongs to. Do you remember the bad reuse of <code>InvalidDataException</code> which is actually defined in the <code>System.IO</code> namespace? The fact that it belongs to this namespace means this type of exception can be thrown from classes that are in the <code>System.IO</code> namespace or in a more nested one. But the actual exception was thrown from a completely different space, confusing a person that handles the issue. However, if you put the types of exceptions and the types that throw these exceptions in the same namespaces you keep the architecture of types consistent and make it easier for developers to understand the reasons for what happens.</p>
<p>What is the second way for grouping on the level of code? Inheritance:</p>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>

<span style="color:Blue;">public</span> <span style="color:Blue;">abstract</span> <span style="color:Blue;">class</span> LoggerExceptionBase : Exception
{
    <span style="color:Blue;">protected</span> LoggerException(..);
}

<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> IOLoggerException : LoggerExceptionBase
{
    <span style="color:Blue;">internal</span> IOLoggerException(..);
}

<span style="color:Blue;">public</span> <span style="color:Blue;">class</span> ConfigLoggerException : LoggerExceptionBase
{
    <span style="color:Blue;">internal</span> ConfigLoggerException(..);
}

</pre></div>
</div>
<p>Note that for usual application entities, they inherit both behavior and data and group types that belong to a <em>single group of entities</em>. However, for exceptions, they inherit and are grouped based on a <em>single group of situations</em>, because the essence of an exception is not an entity but a problem.</p>
<p>Combining these two grouping methods we can make the following conclusions:</p>
<ul>
<li>there should be a base type of exceptions inside <code>Assembly</code> that will be thrown by this assembly. This type of exceptions should be in a root namespace of the assembly. This will be the first layer of grouping.</li>
<li>further, there can be one or several namespaces inside an assembly. Each of them divides the assembly into functional zones, defining the groups of situations, that appear in this assembly. These may be zones of controllers, database entities, data processing algorithms, etc. For us, these namespaces mean grouping types based on their function. However, in terms of exceptions they are grouped based on problems within the same assembly;</li>
<li>exceptions must be inherited from types in the same upper-level namespace. This ensures that end user will unambiguously understand situations and won’t catch <em>wrong</em> type based exceptions. Admit, it would be strange to catch <code>global::Finiki.Logistics.OhMyException</code> by <code>catch(global::Legacy.LoggerExeption exception)</code>, while the following code looks absolutely appropriate:</li>
</ul>
<div class="lang-csharp editor-colors"><div style="color:Black;background-color:White;"><pre>
<span style="color:Blue;">namespace</span> JetFinance.FinancialPipe
{
    <span style="color:Blue;">namespace</span> Services.XmlParserService
    {
        <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> XmlParserServiceException : FinancialPipeExceptionBase
        {
            <span style="color:Green;">// ..</span>
        }

        <span style="color:Blue;">public</span> <span style="color:Blue;">class</span> Parser
        {
            <span style="color:Blue;">public</span> <span style="color:Blue;">void</span> Parse(<span style="color:Blue;">string</span> input)
            {
                <span style="color:Green;">// ..</span>
            }
        }
    }

    <span style="color:Blue;">public</span> <span style="color:Blue;">abstract</span> <span style="color:Blue;">class</span> FinancialPipeExceptionBase : Exception
    {

    }
}

<span style="color:Blue;">using</span> JetFinance.FinancialPipe;
<span style="color:Blue;">using</span> JetFinance.FinancialPipe.Services.XmlParserService;

<span style="color:Blue;">var</span> parser = <span style="color:Blue;">new</span> Parser();

<span style="color:Blue;">try</span> {
    parser.Parse();
}
<span style="color:Blue;">catch</span> (XmlParserServiceException exception)
{
    <span style="color:Green;">// Something is wrong in the parser</span>
}
<span style="color:Blue;">catch</span> (FinancialPipeExceptionBase exception)
{
    <span style="color:Green;">// Something else is wrong. Looks critical because we don&#39;t know the real reason</span>
}

</pre></div>
</div>
<p>Here, the user code calls a library method that, as we know, can throw <code>XmlParserServiceException</code> in some situation. And, as we know, this exception refers to the inherited namespace <code>JetFinance.FinancialPipe.FinancialPipeExceptionBase</code>, which means that there may be some other exceptions — this time <code>XmlParserService</code> microservice creates only one exception but other exceptions may appear in future. As we have a convention for creating types of exceptions, we know what entity this new exception will be inherited from and put an encompassing <code>catch</code> in advance. That enables us to skip all things irrelevant to us.</p>
<p>How to build such a hierarchy of types?</p>
<ul>
<li>First of all, we should create a base class for a domain. Let’s call it a domain base class. In this case, a domain is a word that encompasses a number of assemblies, combining them based on some feature: logging, business-logic, UI. I mean functional zones of an application that are as large as possible.</li>
<li>Next, we should introduce an additional base class for exceptions which must be caught: all the exceptions that will be caught using the <code>catch</code> keyword will be inherited from this base class;</li>
<li>All the exceptions indicating fatal errors should be inherited directly from a domain base class. Thus we will separate them from those caught on the architecture level;
– Divide the domain into functional areas based on namespaces and declare the base type of exceptions that will be thrown from each area. Here it is necessary to use common sense: if an application has a high degree of namespace nesting, you shouldn’t do a base type for each nesting level. However, if there is branching at a nesting level when one group of exceptions goes to one namespace and another group goes to another namespace, it is necessary to use two base types for each subgroup;</li>
<li>Special exceptions should be inherited from the types of exceptions belonging to functional areas</li>
<li>If a group of special exceptions can be combined, it is necessary to do it in one more base type: thus you can catch them easier;</li>
<li>If you suppose the group will be more often caught using a base class, introduce Mixed Mode with ErrorCode.</li>
</ul>
<h3 id="based-on-the-source-of-an-error">Based on the source of an error</h3>
<p>The source of an error can be another basis to combine exceptions in a group. For example, if you design a class library, the following things can form groups of sources:</p>
<ul>
<li>unsafe code call with an error. This situation can be dealt with by wrapping an exception or an error code in its own type of exception while saving returned data (for example the original error code) in a public property of the exception;</li>
<li>a call of code by external dependencies, which has thrown exceptions that can’t be caught by our library as they are beyond its area of responsibility. This group can include exceptions from the methods of those entities that were accepted as the parameters of a current method or exceptions from the constructor of a class which method has called an external dependence. For example, a method of our class has called a method of another class, the instance of which was returned via parameters of another method. If an exception indicates that we are the source of a problem, we should generate our own exception while retaining the original one in <code>InnerExcepton</code>. However, if we understand that the problem has been caused by an external dependency we ignore this exception as belonging to a group of external dependencies beyond our control;</li>
<li>our own code that was accidentally put in an inconsistent state. A good example is text parsing — no external dependencies, no transfer to <code>unsafe</code> world, but a problem of parsing occurs.</li>
</ul>

</div>
</div>
</body>
</html>